#!/usr/bin/env bash
# File: kauto_double.sh

FILE1=$1
FILE2=$2
OUT=$3
#INDEX="/home/users/dberl/projects_current/VER01/gen29.idx"
#OUTPUT="/home/users/dberl/projects_current/VER01/$OUT"

kallisto quant -i $INDEX -o $OUT $FILE1 $FILE2



